name: GH-docker-deploy-DEV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production Server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME}}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            cd ~/compose-folder
            docker pull ghcr.io/abelmv29/dotnet-api:latest
            docker compose up -d
