# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: GH-docker-registry-DEV

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t ghcr.io/abelmv29/dotnet-api:latest .
    - name: Sign in GitHub Registry
      run: echo ${ secrets.ACCESS_TOKEN_GH } | docker login ghcr.io -u abelmv29 --password-stdin
    - name: Push images to GitHub Registry
      run: docker push ghcr.io/abelmv29/dotnet-api:latest
